// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPSIDs
{
        public const string achievement_played_25_rounds_of_battleship_cardbaord = "CgkItJjHi7YMEAIQBQ"; // <GPGSID>
        public const string achievement_won_five_rounds_of_battleship_cardbaord = "CgkItJjHi7YMEAIQAw"; // <GPGSID>
        public const string achievement_played_one_round_of_battleship_cardboard = "CgkItJjHi7YMEAIQAQ"; // <GPGSID>
        public const string achievement_played_ten_rounds_of_battleship_cardboard = "CgkItJjHi7YMEAIQAg"; // <GPGSID>
        public const string achievement_won_ten_rounds_of_battleship_cardbaord = "CgkItJjHi7YMEAIQBA"; // <GPGSID>

}

