public enum ConnectionStatus
{
	GAME_TYPE_SELECTION_REQUIRED,
	AUTHENTICATION_REQUIRED,
	AUTHENTICATED_NO_GAME,
	AUTHENTICATED_SETTING_UP_GAME,
	AUTHENTICATED_TEARING_DOWN_GAME,
	AUTHENTICATED_IN_GAME,
}